definitions:
  datasource.CreateUserReq:
    properties:
      name:
        type: string
    type: object
  datasource.User:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  entity.GetUsersResp:
    properties:
      total:
        type: integer
      users:
        items:
          $ref: '#/definitions/datasource.User'
        type: array
    type: object
  entity.Response:
    properties:
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    get:
      parameters:
      - description: Jika tidak memasukkan user ID maka akan get semua
        in: query
        name: id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.GetUsersResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Response'
      summary: mengambil data-data user
      tags:
      - User
    post:
      parameters:
      - description: request body JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/datasource.CreateUserReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
      summary: Membuat user baru
      tags:
      - User
  /user/{id}:
    delete:
      parameters:
      - description: User ID (angka positif)
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
      summary: Menghapus data user by ID
      tags:
      - User
    put:
      parameters:
      - description: User ID (angka positif)
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
      summary: mengubah data user berdasarkan ID
      tags:
      - User
swagger: "2.0"
